# Generated by Django 3.1.7 on 2021-03-25 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'Subcategories'},
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='subcategory',
            new_name='sucategory',
        ),
        migrations.RemoveField(
            model_name='category',
            name='subcatgeory_1',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='catgeory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
