# Generated by Django 3.1.7 on 2021-03-25 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_subcategorylevel2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='sucategory',
            new_name='subcategory',
        ),
    ]
