# Generated by Django 3.1.7 on 2021-03-27 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20210327_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocart',
            name='name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
    ]
