# Generated by Django 3.1.7 on 2021-03-27 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20210327_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtocart',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
    ]
