# Generated by Django 3.1.7 on 2021-03-27 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20210327_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='add_to_cart',
        ),
        migrations.AddField(
            model_name='orders',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
    ]
