# Generated by Django 3.1.7 on 2021-03-27 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_orders_delivered'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_products_sold', models.IntegerField(null=True)),
                ('turnover_gained', models.IntegerField(blank=True)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.seller')),
            ],
        ),
    ]
