# Generated by Django 3.1.7 on 2021-03-30 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_auto_20210330_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='seller',
        ),
    ]
